### ISSUE TITLE
Extract the kubeconfig file

### ISSUE THREAD

**Issue by yerdreic** [crc-org/crc-cloud#12]
Extract the kubeconfig file and put it in the current location so user can use it for long term.

**Comment by praveenkumar** [comment]
This kubeconfig file is in the instance and need to be scp from cloud instance to host after provision.

**Comment by lmilbaum** [comment]
> This kubeconfig file is in the instance and need to be scp from cloud instance to host after provision.

I think there are ways to provide the `kubeconfig` file during the provisioning phase.

**Comment by tsebastiani** [comment]
Can be easily done, even though an ```oc login``` either with the default or with the provided credentials will create a new one for you on your home folder or in the path specified on KUBECONFIG env var
