### ISSUE TITLE
[suggestion] logo

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc-cloud#13]
played around a little and came up with a logo idea for crc cloud

~image removed~

this is a nod to our laptop logo for crc, and the webcam-dot referring to spot.
Suggestions or comments?

---

The copyright for generated images is questionable and rather want we own the 'source' of the image.

**Comment by cfergeau** [comment]
Dunno if the dot is  required? Would look better with curved end of lines instead of the current straight ones around the dot
`=(o)=` (imagine this is the area around the dot :) instead of `=|o|=`

**Comment by gbraad** [comment]
@cfergeau was the easiest to get done quickly. Wanted more feedback before continuing.

**Comment by tsebastiani** [comment]
If you manage to round the edges near the dot and increase a little bit the space around it (like the crc logo) is perfect! 👍🏻🤩

**Comment by gbraad** [comment]
![](https://cloud.gbraad.nl/s/2D6LiSx3Mci4wQw/preview)

**Comment by tsebastiani** [comment]
Do we want to change the logo?

**Comment by praveenkumar** [comment]
This logo looks better so let's update it.

**Comment by gbraad** [comment]
Will make a PR
