### ISSUE TITLE
Add CI to this repo

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc-cloud#19]
As of now we are not sure if some PR break existing workflow and it is not possible to test end to end flow for each PR so better to have a CI job in place which take of it. I have openshift-ci in mind but if someone have better suggestion/option do put in comment.

**Comment by lmilbaum** [comment]
Activating CI is a GREAT idea. Do you know if openshift-ci can be used to spin an environment? for example: CRC on AWS.

**Comment by praveenkumar** [comment]
@lmilbaum yes we use openshift-ci for crc use case https://github.com/openshift/release/tree/master/ci-operator/step-registry/code-ready/crc and I had experience to adding the configuration for CI , I would happy to assist if someone want to take a look, documentations are also good starting point https://docs.ci.openshift.org/docs/getting-started/

**Comment by lmilbaum** [comment]
I would prefer we start with GitHub Actions and expand as needed

**Comment by adrianriobo** [comment]
^^ @lmilbaum you were interested in this.... I did not dig a lot on how this is setup..but on pulumi they setup this flow for running the checks..which involves some AWS credentials....

https://github.com/pulumi/pulumi-command/pull/180

basically a maintainer should run the acceptance from there actions are executed ...

https://github.com/pulumi/pulumi-command/actions/runs/4007312915/jobs/6880059455

there is a step "Configure AWS Credentials" which setups the credentials for AWS 

not sure if you already covered this flow and you were looking for some extension on forked repos...or you were looking for something like this

**Comment by adrianriobo** [comment]
sorry so may I misunderstood :( so then what was the context when we talked about the GitHub Actions and the topic on AWS credentials (about not using it when PR comes from a forked?)

**Comment by lmilbaum** [comment]
> sorry so may I misunderstood :( so then what was the context when we talked about the GitHub Actions and the topic on AWS credentials (about not using it when PR comes from a forked?)

I described a project of mine which is not utilizing Openshift CI

**Comment by adrianriobo** [comment]
As per @lmilbaum  it would be great to include renovate to help us solving dependencies #46
