### ISSUE TITLE
typo usuage instead of usage

### ISSUE THREAD

**Issue by ilkomiliev** [crc-org/crc-cloud#29]
https://github.com/crc-org/crc-cloud/blob/6869ce2ee817066b3cc02836f0323d3e1893360a/crc-cloud.sh#L196

**Comment by praveenkumar** [comment]
@ilkomiliev you can put a PR to fix this typo :)

**Comment by ilkomiliev** [comment]
done: https://github.com/crc-org/crc-cloud/pull/31

**Comment by ilkomiliev** [comment]
thanks for pointing this out - I hope I amended the commit message now as requested, otherwise pls let me know

thanks!
